//
// Created by bakatrouble on 10/11/22.
//

#ifndef KEYPAD_CMSIS_FREERTOS_DEVICE_INPUT_PINS_H
#define KEYPAD_CMSIS_FREERTOS_DEVICE_INPUT_PINS_H

#define PUSH1_Pin GPIO_PIN_0
#define PUSH2_Pin GPIO_PIN_1
#define COL1_Pin GPIO_PIN_13
#define COL2_Pin GPIO_PIN_14
#define COL3_Pin GPIO_PIN_15
#define ROT_A_Pin GPIO_PIN_0
#define ROT_B_Pin GPIO_PIN_1
#define ROT_PUSH_Pin GPIO_PIN_3
#define ROW1_Pin GPIO_PIN_6
#define ROW2_Pin GPIO_PIN_7
#define ROW3_Pin GPIO_PIN_8
#define ROW4_Pin GPIO_PIN_9
#define ROW5_Pin GPIO_PIN_10

#endif //KEYPAD_CMSIS_FREERTOS_DEVICE_INPUT_PINS_H
